### ISSUE TITLE
Data import: Remove jsonschema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/notebooks-oc4ids#24]
Once https://github.com/OpenDataServices/lib-cove/pull/92 is merged and release on Pypi we can remove the JSON schema line from [this cell](https://github.com/OpenDataServices/lib-cove/pull/92).

**Comment by jpmckinney** [comment]
Noting that PR is merged: https://github.com/OpenDataServices/lib-cove/pull/94

**Comment by duncandewhurst** [comment]
Thanks! I've added the change to https://github.com/open-contracting/notebooks-oc4ids/pull/36
